package com.kronos.multiplatform.weatherapp.components.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Composable
fun AppTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable() () -> Unit
) {
    val colorScheme = when {
        darkTheme -> darkScheme
        else -> lightScheme
    }

    MaterialTheme(
        colorScheme = colorScheme,
        typography = OpenSansTypography,
        content = content
    )
}

@Immutable
data class ExtendedColorScheme(
    val primaryLigth: ColorFamily,
    val text: ColorFamily,
    val icon: ColorFamily,
    val divider: ColorFamily,
    val error: ColorFamily,
    val cardBackground: ColorFamily,
    val layoutBackground: ColorFamily,
    val ratingColor: ColorFamily,
    val currentStep: ColorFamily,
    val completedStep: ColorFamily,
    val incompletedStep: ColorFamily,
)

private val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

private val mediumContrastLightColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val highContrastLightColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val mediumContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val highContrastDarkColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)

val extendedLight = ExtendedColorScheme(
    primaryLigth = ColorFamily(
        primaryLigthLight,
        onPrimaryLigthLight,
        primaryLigthContainerLight,
        onPrimaryLigthContainerLight,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    text = ColorFamily(
        textLight,
        onTextLight,
        textContainerLight,
        onTextContainerLight,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    icon = ColorFamily(
        iconLight,
        onIconLight,
        iconContainerLight,
        onIconContainerLight,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    divider = ColorFamily(
        dividerLight,
        onDividerLight,
        dividerContainerLight,
        onDividerContainerLight,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    error = ColorFamily(
        errorLight,
        onErrorLight,
        errorContainerLight,
        onErrorContainerLight,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    cardBackground = ColorFamily(
        cardBackgroundLight,
        onCardBackgroundLight,
        cardBackgroundContainerLight,
        onCardBackgroundContainerLight,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    layoutBackground = ColorFamily(
        layoutBackgroundLight,
        onLayoutBackgroundLight,
        layoutBackgroundContainerLight,
        onLayoutBackgroundContainerLight,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    ratingColor = ColorFamily(
        ratingColorLight,
        onRatingColorLight,
        ratingColorContainerLight,
        onRatingColorContainerLight,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    currentStep = ColorFamily(
        currentStepLight,
        onCurrentStepLight,
        currentStepContainerLight,
        onCurrentStepContainerLight,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    completedStep = ColorFamily(
        completedStepLight,
        onCompletedStepLight,
        completedStepContainerLight,
        onCompletedStepContainerLight,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    incompletedStep = ColorFamily(
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
)

val extendedDark = ExtendedColorScheme(
    primaryLigth = ColorFamily(
        primaryLigthDark,
        onPrimaryLigthDark,
        primaryLigthContainerDark,
        onPrimaryLigthContainerDark,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    text = ColorFamily(
        textDark,
        onTextDark,
        textContainerDark,
        onTextContainerDark,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    icon = ColorFamily(
        iconDark,
        onIconDark,
        iconContainerDark,
        onIconContainerDark,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    divider = ColorFamily(
        dividerDark,
        onDividerDark,
        dividerContainerDark,
        onDividerContainerDark,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    error = ColorFamily(
        errorDark,
        onErrorDark,
        errorContainerDark,
        onErrorContainerDark,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    cardBackground = ColorFamily(
        cardBackgroundDark,
        onCardBackgroundDark,
        cardBackgroundContainerDark,
        onCardBackgroundContainerDark,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    layoutBackground = ColorFamily(
        layoutBackgroundDark,
        onLayoutBackgroundDark,
        layoutBackgroundContainerDark,
        onLayoutBackgroundContainerDark,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    ratingColor = ColorFamily(
        ratingColorDark,
        onRatingColorDark,
        ratingColorContainerDark,
        onRatingColorContainerDark,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    currentStep = ColorFamily(
        currentStepDark,
        onCurrentStepDark,
        currentStepContainerDark,
        onCurrentStepContainerDark,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    completedStep = ColorFamily(
        completedStepDark,
        onCompletedStepDark,
        completedStepContainerDark,
        onCompletedStepContainerDark,
        incompletedStepDark,
        onIncompletedStepDark,
        incompletedStepContainerDark,
        onIncompletedStepContainerDark,
    ),
    incompletedStep = ColorFamily(
        incompletedStepDark,
        onIncompletedStepDark,
        incompletedStepContainerDark,
        onIncompletedStepContainerDark,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
)

val extendedLightMediumContrast = ExtendedColorScheme(
    primaryLigth = ColorFamily(
        primaryLigthLightMediumContrast,
        onPrimaryLigthLightMediumContrast,
        primaryLigthContainerLightMediumContrast,
        onPrimaryLigthContainerLightMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    text = ColorFamily(
        textLightMediumContrast,
        onTextLightMediumContrast,
        textContainerLightMediumContrast,
        onTextContainerLightMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    icon = ColorFamily(
        iconLightMediumContrast,
        onIconLightMediumContrast,
        iconContainerLightMediumContrast,
        onIconContainerLightMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    divider = ColorFamily(
        dividerLightMediumContrast,
        onDividerLightMediumContrast,
        dividerContainerLightMediumContrast,
        onDividerContainerLightMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    error = ColorFamily(
        errorLightMediumContrast,
        onErrorLightMediumContrast,
        errorContainerLightMediumContrast,
        onErrorContainerLightMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    cardBackground = ColorFamily(
        cardBackgroundLightMediumContrast,
        onCardBackgroundLightMediumContrast,
        cardBackgroundContainerLightMediumContrast,
        onCardBackgroundContainerLightMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    layoutBackground = ColorFamily(
        layoutBackgroundLightMediumContrast,
        onLayoutBackgroundLightMediumContrast,
        layoutBackgroundContainerLightMediumContrast,
        onLayoutBackgroundContainerLightMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    ratingColor = ColorFamily(
        ratingColorLightMediumContrast,
        onRatingColorLightMediumContrast,
        ratingColorContainerLightMediumContrast,
        onRatingColorContainerLightMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    currentStep = ColorFamily(
        currentStepLightMediumContrast,
        onCurrentStepLightMediumContrast,
        currentStepContainerLightMediumContrast,
        onCurrentStepContainerLightMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    completedStep = ColorFamily(
        completedStepLightMediumContrast,
        onCompletedStepLightMediumContrast,
        completedStepContainerLightMediumContrast,
        onCompletedStepContainerLightMediumContrast,
        incompletedStepLightMediumContrast,
        onIncompletedStepLightMediumContrast,
        incompletedStepContainerLightMediumContrast,
        onIncompletedStepContainerLightMediumContrast,
    ),
    incompletedStep = ColorFamily(
        incompletedStepLightMediumContrast,
        onIncompletedStepLightMediumContrast,
        incompletedStepContainerLightMediumContrast,
        onIncompletedStepContainerLightMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
)

val extendedLightHighContrast = ExtendedColorScheme(
    primaryLigth = ColorFamily(
        primaryLigthLightHighContrast,
        onPrimaryLigthLightHighContrast,
        primaryLigthContainerLightHighContrast,
        onPrimaryLigthContainerLightHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    text = ColorFamily(
        textLightHighContrast,
        onTextLightHighContrast,
        textContainerLightHighContrast,
        onTextContainerLightHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    icon = ColorFamily(
        iconLightHighContrast,
        onIconLightHighContrast,
        iconContainerLightHighContrast,
        onIconContainerLightHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    divider = ColorFamily(
        dividerLightHighContrast,
        onDividerLightHighContrast,
        dividerContainerLightHighContrast,
        onDividerContainerLightHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    error = ColorFamily(
        errorLightHighContrast,
        onErrorLightHighContrast,
        errorContainerLightHighContrast,
        onErrorContainerLightHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    cardBackground = ColorFamily(
        cardBackgroundLightHighContrast,
        onCardBackgroundLightHighContrast,
        cardBackgroundContainerLightHighContrast,
        onCardBackgroundContainerLightHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    layoutBackground = ColorFamily(
        layoutBackgroundLightHighContrast,
        onLayoutBackgroundLightHighContrast,
        layoutBackgroundContainerLightHighContrast,
        onLayoutBackgroundContainerLightHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    ratingColor = ColorFamily(
        ratingColorLightHighContrast,
        onRatingColorLightHighContrast,
        ratingColorContainerLightHighContrast,
        onRatingColorContainerLightHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    currentStep = ColorFamily(
        currentStepLightHighContrast,
        onCurrentStepLightHighContrast,
        currentStepContainerLightHighContrast,
        onCurrentStepContainerLightHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    completedStep = ColorFamily(
        completedStepLightHighContrast,
        onCompletedStepLightHighContrast,
        completedStepContainerLightHighContrast,
        onCompletedStepContainerLightHighContrast,
        incompletedStepLightHighContrast,
        onIncompletedStepLightHighContrast,
        incompletedStepContainerLightHighContrast,
        onIncompletedStepContainerLightHighContrast,
    ),
    incompletedStep = ColorFamily(
        incompletedStepLightHighContrast,
        onIncompletedStepLightHighContrast,
        incompletedStepContainerLightHighContrast,
        onIncompletedStepContainerLightHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
)

val extendedDarkMediumContrast = ExtendedColorScheme(
    primaryLigth = ColorFamily(
        primaryLigthDarkMediumContrast,
        onPrimaryLigthDarkMediumContrast,
        primaryLigthContainerDarkMediumContrast,
        onPrimaryLigthContainerDarkMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    text = ColorFamily(
        textDarkMediumContrast,
        onTextDarkMediumContrast,
        textContainerDarkMediumContrast,
        onTextContainerDarkMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    icon = ColorFamily(
        iconDarkMediumContrast,
        onIconDarkMediumContrast,
        iconContainerDarkMediumContrast,
        onIconContainerDarkMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    divider = ColorFamily(
        dividerDarkMediumContrast,
        onDividerDarkMediumContrast,
        dividerContainerDarkMediumContrast,
        onDividerContainerDarkMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    error = ColorFamily(
        errorDarkMediumContrast,
        onErrorDarkMediumContrast,
        errorContainerDarkMediumContrast,
        onErrorContainerDarkMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    cardBackground = ColorFamily(
        cardBackgroundDarkMediumContrast,
        onCardBackgroundDarkMediumContrast,
        cardBackgroundContainerDarkMediumContrast,
        onCardBackgroundContainerDarkMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    layoutBackground = ColorFamily(
        layoutBackgroundDarkMediumContrast,
        onLayoutBackgroundDarkMediumContrast,
        layoutBackgroundContainerDarkMediumContrast,
        onLayoutBackgroundContainerDarkMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    ratingColor = ColorFamily(
        ratingColorDarkMediumContrast,
        onRatingColorDarkMediumContrast,
        ratingColorContainerDarkMediumContrast,
        onRatingColorContainerDarkMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    currentStep = ColorFamily(
        currentStepDarkMediumContrast,
        onCurrentStepDarkMediumContrast,
        currentStepContainerDarkMediumContrast,
        onCurrentStepContainerDarkMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    completedStep = ColorFamily(
        completedStepDarkMediumContrast,
        onCompletedStepDarkMediumContrast,
        completedStepContainerDarkMediumContrast,
        onCompletedStepContainerDarkMediumContrast,
        incompletedStepDarkMediumContrast,
        onIncompletedStepDarkMediumContrast,
        incompletedStepContainerDarkMediumContrast,
        onIncompletedStepContainerDarkMediumContrast,
    ),
    incompletedStep = ColorFamily(
        incompletedStepDarkMediumContrast,
        onIncompletedStepDarkMediumContrast,
        incompletedStepContainerDarkMediumContrast,
        onIncompletedStepContainerDarkMediumContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
)

val extendedDarkHighContrast = ExtendedColorScheme(
    primaryLigth = ColorFamily(
        primaryLigthDarkHighContrast,
        onPrimaryLigthDarkHighContrast,
        primaryLigthContainerDarkHighContrast,
        onPrimaryLigthContainerDarkHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    text = ColorFamily(
        textDarkHighContrast,
        onTextDarkHighContrast,
        textContainerDarkHighContrast,
        onTextContainerDarkHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    icon = ColorFamily(
        iconDarkHighContrast,
        onIconDarkHighContrast,
        iconContainerDarkHighContrast,
        onIconContainerDarkHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    divider = ColorFamily(
        dividerDarkHighContrast,
        onDividerDarkHighContrast,
        dividerContainerDarkHighContrast,
        onDividerContainerDarkHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    error = ColorFamily(
        errorDarkHighContrast,
        onErrorDarkHighContrast,
        errorContainerDarkHighContrast,
        onErrorContainerDarkHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    cardBackground = ColorFamily(
        cardBackgroundDarkHighContrast,
        onCardBackgroundDarkHighContrast,
        cardBackgroundContainerDarkHighContrast,
        onCardBackgroundContainerDarkHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    layoutBackground = ColorFamily(
        layoutBackgroundDarkHighContrast,
        onLayoutBackgroundDarkHighContrast,
        layoutBackgroundContainerDarkHighContrast,
        onLayoutBackgroundContainerDarkHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    ratingColor = ColorFamily(
        ratingColorDarkHighContrast,
        onRatingColorDarkHighContrast,
        ratingColorContainerDarkHighContrast,
        onRatingColorContainerDarkHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    currentStep = ColorFamily(
        currentStepDarkHighContrast,
        onCurrentStepDarkHighContrast,
        currentStepContainerDarkHighContrast,
        onCurrentStepContainerDarkHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
    completedStep = ColorFamily(
        completedStepDarkHighContrast,
        onCompletedStepDarkHighContrast,
        completedStepContainerDarkHighContrast,
        onCompletedStepContainerDarkHighContrast,
        incompletedStepDarkHighContrast,
        onIncompletedStepDarkHighContrast,
        incompletedStepContainerDarkHighContrast,
        onIncompletedStepContainerDarkHighContrast,
    ),
    incompletedStep = ColorFamily(
        incompletedStepDarkHighContrast,
        onIncompletedStepDarkHighContrast,
        incompletedStepContainerDarkHighContrast,
        onIncompletedStepContainerDarkHighContrast,
        incompletedStepLight,
        onIncompletedStepLight,
        incompletedStepContainerLight,
        onIncompletedStepContainerLight,
    ),
)

@Immutable
data class ColorFamily(
    val color: Color,
    val onColor: Color,
    val colorContainer: Color,
    val onColorContainer: Color,
    val incompletedStepLight: Color,
    val onIncompletedStepLight: Color,
    val incompletedStepContainerLight: Color,
    val onIncompletedStepContainerLight: Color
)

val unspecified_scheme = ColorFamily(
    Color.Unspecified,
    Color.Unspecified,
    Color.Unspecified,
    Color.Unspecified,
    incompletedStepLight,
    onIncompletedStepLight,
    incompletedStepContainerLight,
    onIncompletedStepContainerLight
)
